In [2]:
import pandas as pd
import time
import torch

## Загрузка данных

In [3]:
df = pd.read_csv('data/data.csv')
df.head()

Unnamed: 0     id  episode_id  number  \
0           0  10368          35      29   
1           1  10369          35      30   
2           2  10370          35      31   
3           3  10372          35      33   
4           4  10374          35      35   

                                            raw_text  timestamp_in_ms  \
0           Lisa Simpson: Maggie, look. What's that?           235000   
1                    Lisa Simpson: Lee-mur. Lee-mur.           237000   
2                    Lisa Simpson: Zee-boo. Zee-boo.           239000   
3  Lisa Simpson: I'm trying to teach Maggie that ...           245000   
4  Lisa Simpson: It's like an ox, only it has a h...           254000   

   speaking_line  character_id  location_id raw_character_text  \
0           True             9          5.0       Lisa Simpson   
1           True             9          5.0       Lisa Simpson   
2           True             9          5.0       Lisa Simpson   
3           True             9          5.0       Lisa Simpson   
4           True             9          5.0       Lisa Simpson   

  raw_location_text                                       spoken_words  \
0      Simpson Home                         Maggie, look. What's that?   
1      Simpson Home                                  Lee-mur. Lee-mur.   
2      Simpson Home                                  Zee-boo. Zee-boo.   
3      Simpson Home  I'm trying to teach Maggie that nature doesn't...   
4      Simpson Home  It's like an ox, only it has a hump and a dewl...   

                                     normalized_text  word_count  
0                             maggie look whats that         4.0  
1                                    lee-mur lee-mur         2.0  
2                                    zee-boo zee-boo         2.0  
3  im trying to teach maggie that nature doesnt e...        24.0  
4  its like an ox only it has a hump and a dewlap...        18.0

In [6]:
phrases = df['normalized_text'].tolist()
phrases[:10]

['maggie look whats that',
 'lee-mur lee-mur',
 'zee-boo zee-boo',
 'im trying to teach maggie that nature doesnt end with the barnyard i want her to have all the advantages that i didnt have',
 'its like an ox only it has a hump and a dewlap hump and dew-lap hump and dew-lap',
 'you know his blood type how romantic',
 'oh yeah whats my shoe size',
 'ring',
 'yes dad',
 'ooh look maggie what is that do-dec-ah-edron dodecahedron']

In [8]:
text = [[c for c in ph] for ph in phrases if type(ph) is str]

## Делаем массив с данными

In [11]:
CHARS = set('abcdefghijklmnopqrstuvwxyz ')
INDEX_TO_CHAR = ['none'] + [w for w in CHARS]
CHAR_TO_INDEX = {w: i for i, w in enumerate(INDEX_TO_CHAR)}

In [12]:
MAX_LEN = 50
X = torch.zeros((len(text), MAX_LEN), dtype=int)
for i in range(len(text)):
    for j, w in enumerate(text[i]):
        if j >= MAX_LEN:
            break
        X[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [13]:
X[0:10]

tensor([[27,  5, 19, 19, 25,  6,  1, 15, 21, 21, 18,  1,  2,  4,  5, 24, 23,  1,
         24,  4,  5, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [15,  6,  6,  0, 27, 17, 22,  1, 15,  6,  6,  0, 27, 17, 22,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [20,  6,  6,  0, 13, 21, 21,  1, 20,  6,  6,  0, 13, 21, 21,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [25, 27,  1, 24, 22, 26, 25,  7, 19,  1, 24, 21,  1, 24,  6,  5,  8,  4,
          1, 27,  5, 19, 19, 25,  6,  1, 24,  4,  5, 24,  1,  7,  5, 24, 17, 22,
          6,  1,  3, 21,  6, 23,  7, 24,  1,  6,  7,  3,  1,  2],
        [25, 24, 23,  1, 15, 25, 18,  6,  1,  5,  7,  1, 21, 16,  1, 21,  7, 15,
       

In [42]:
import numpy as np 

In [49]:
chars = set('abcdefghijklmnopqrstuvwxyz')
index_to_char = sorted([w for w in chars])
char_to_index = {i: k for i, k in zip(index_to_char, np.roll(np.array(index_to_char), 5))}

In [50]:
char_to_index

{'a': 'v',
 'b': 'w',
 'c': 'x',
 'd': 'y',
 'e': 'z',
 'f': 'a',
 'g': 'b',
 'h': 'c',
 'i': 'd',
 'j': 'e',
 'k': 'f',
 'l': 'g',
 'm': 'h',
 'n': 'i',
 'o': 'j',
 'p': 'k',
 'q': 'l',
 'r': 'm',
 's': 'n',
 't': 'o',
 'u': 'p',
 'v': 'q',
 'w': 'r',
 'x': 's',
 'y': 't',
 'z': 'u'}

In [60]:
codes = [''.join([char_to_index.get(letter, ' ') for letter in phrase]) for phrase in phrases if type(phrase) is str]
codes[:10]   

['hvbbdz gjjf rcvon ocvo',
 'gzz hpm gzz hpm',
 'uzz wjj uzz wjj',
 'dh omtdib oj ozvxc hvbbdz ocvo ivopmz yjznio ziy rdoc ocz wvmitvmy d rvio czm oj cvqz vgg ocz vyqviovbzn ocvo d ydyio cvqz',
 'don gdfz vi js jigt do cvn v cphk viy v yzrgvk cphk viy yzr gvk cphk viy yzr gvk',
 'tjp fijr cdn wgjjy otkz cjr mjhviodx',
 'jc tzvc rcvon ht ncjz nduz',
 'mdib',
 'tzn yvy',
 'jjc gjjf hvbbdz rcvo dn ocvo yj yzx vc zymji yjyzxvczymji']

In [61]:
text_codes = [[c for c in ph] for ph in codes if type(ph) is str]

In [63]:
MAX_LEN = 50
Y = torch.zeros((len(text_codes), MAX_LEN), dtype=int)
for i in range(len(text_codes)):
    for j, w in enumerate(text_codes[i]):
        if j >= MAX_LEN:
            break
        Y[i, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [65]:
X[:10]

tensor([[27,  5, 19, 19, 25,  6,  1, 15, 21, 21, 18,  1,  2,  4,  5, 24, 23,  1,
         24,  4,  5, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [15,  6,  6,  0, 27, 17, 22,  1, 15,  6,  6,  0, 27, 17, 22,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [20,  6,  6,  0, 13, 21, 21,  1, 20,  6,  6,  0, 13, 21, 21,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [25, 27,  1, 24, 22, 26, 25,  7, 19,  1, 24, 21,  1, 24,  6,  5,  8,  4,
          1, 27,  5, 19, 19, 25,  6,  1, 24,  4,  5, 24,  1,  7,  5, 24, 17, 22,
          6,  1,  3, 21,  6, 23,  7, 24,  1,  6,  7,  3,  1,  2],
        [25, 24, 23,  1, 15, 25, 18,  6,  1,  5,  7,  1, 21, 16,  1, 21,  7, 15,
       

In [64]:
Y[:10]

tensor([[ 4, 12, 13, 13,  3, 20,  1, 19, 11, 11, 14,  1, 22,  8, 12, 21,  7,  1,
         21,  8, 12, 21,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [19, 20, 20,  1,  4, 10, 27,  1, 19, 20, 20,  1,  4, 10, 27,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [17, 20, 20,  1,  2, 11, 11,  1, 17, 20, 20,  1,  2, 11, 11,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 3,  4,  1, 21, 27, 24,  3, 25, 13,  1, 21, 11,  1, 21, 20, 12, 16,  8,
          1,  4, 12, 13, 13,  3, 20,  1, 21,  8, 12, 21,  1, 25, 12, 21, 10, 27,
         20,  1, 26, 11, 20,  7, 25, 21,  1, 20, 25, 26,  1, 22],
        [ 3, 21,  7,  1, 19,  3, 14, 20,  1, 12, 25,  1, 11, 23,  1, 11, 25, 19,
       

## Смотрим на Embedding и RNN ячейку

In [14]:
embeddings = torch.nn.Embedding(len(INDEX_TO_CHAR), 28)
t = embeddings(X[0:10])
t

tensor([[[ 0.7027, -0.1612,  0.2037,  ...,  1.3908, -0.2074,  0.1426],
         [-0.6336,  1.0766,  0.4756,  ..., -0.8878, -1.3892,  1.3777],
         [ 0.6949, -1.0634, -3.0977,  ..., -0.4530,  0.5257, -1.9299],
         ...,
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313],
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313],
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313]],

        [[-0.6705,  0.4050,  0.0308,  ..., -1.6747, -1.5839, -0.7379],
         [-0.3925, -0.8849,  0.8152,  ...,  1.5247,  0.5321, -0.3344],
         [-0.3925, -0.8849,  0.8152,  ...,  1.5247,  0.5321, -0.3344],
         ...,
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313],
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313],
         [ 0.4444,  0.9366,  0.2266,  ...,  0.5080,  0.8971, -0.8313]],

        [[ 0.6074,  0.1300,  0.3210,  ...,  0.3276,  1.0478, -1.1171],
         [-0.3925, -0.8849,  0.8152,  ...,  1

In [15]:
t.shape, X[0:10].shape

(torch.Size([10, 50, 28]), torch.Size([10, 50]))

In [28]:
rnn = torch.nn.RNN(28, 128, batch_first=True)
o, s = rnn(t)
o.shape, s.shape

(torch.Size([10, 50, 128]), torch.Size([1, 10, 128]))

In [29]:
o, s2 = rnn(t, s)
o.shape, s2.shape

(torch.Size([10, 50, 128]), torch.Size([1, 10, 128]))

## Практика. Реализуйте код модели нейронной сети
3 слоя - embeding (28), скрытая ячейка (128), полносвязанный из состояния rnn в букву (28)

In [20]:
class Network(torch.nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        ## Здесь создать слои
        self.embed = torch.nn.Embedding(len(CHAR_TO_INDEX), 28)
        self.rnn = torch.nn.RNN(28, 128, batch_first=True)
        self.linear = torch.nn.Linear(128, len(INDEX_TO_CHAR))
        
    def forward(self, sentences, state=None):
        ## Здесь применить
        embed = self.embed(sentences)
        o, s = self.rnn(embed)
        out = self.linear(o)
        return out 

In [21]:
model = Network()

In [22]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=.05)

In [94]:
for ep in range(200):
    start = time.time()
    train_loss = 0.
    train_passed = 0

    for i in range(int(len(X) / 100)):
        batch_X = X[i * 100:(i + 1) * 100]
        batch_Y = Y[i * 100:(i + 1) * 100]
        X_batch = batch_X[:, :-1]
        Y_batch = batch_Y[:, 1:].flatten()

        optimizer.zero_grad()
        answers = model.forward(X_batch)
        answers = answers.view(-1, len(INDEX_TO_CHAR))
        loss = criterion(answers, Y_batch)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        train_passed += 1

    print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(ep, time.time() - start, train_loss / train_passed))

Epoch 0. Time: 2.274, Train loss: 1.100
Epoch 1. Time: 2.172, Train loss: 1.100
Epoch 2. Time: 2.156, Train loss: 1.099
Epoch 3. Time: 2.119, Train loss: 1.099
Epoch 4. Time: 2.200, Train loss: 1.098
Epoch 5. Time: 2.153, Train loss: 1.097
Epoch 6. Time: 2.143, Train loss: 1.097
Epoch 7. Time: 2.115, Train loss: 1.096
Epoch 8. Time: 2.103, Train loss: 1.096
Epoch 9. Time: 2.108, Train loss: 1.095
Epoch 10. Time: 2.263, Train loss: 1.094
Epoch 11. Time: 2.174, Train loss: 1.094
Epoch 12. Time: 2.126, Train loss: 1.093
Epoch 13. Time: 2.119, Train loss: 1.093
Epoch 14. Time: 2.125, Train loss: 1.092
Epoch 15. Time: 2.129, Train loss: 1.092
Epoch 16. Time: 2.127, Train loss: 1.091
Epoch 17. Time: 2.165, Train loss: 1.091
Epoch 18. Time: 2.204, Train loss: 1.090
Epoch 19. Time: 2.201, Train loss: 1.089
Epoch 20. Time: 2.220, Train loss: 1.089
Epoch 21. Time: 2.349, Train loss: 1.088
Epoch 22. Time: 2.490, Train loss: 1.088
Epoch 23. Time: 2.423, Train loss: 1.087
Epoch 24. Time: 2.322, Tra

KeyboardInterrupt: 

## Практика. Реализуйте код генерации следующей буквы на основе модели
Логика такая:
    - Сначала кормим в нее буквы из sentence (прогревая состояние)
    - Затем пока не получим none (0) берем самую вероятную букву и добавляем ее в sentence
    - Повторяем

In [41]:
def generate_sentence():
    sentence = ['h', 'e', 'l', 'l', 'o']
    # Todo

In [95]:
sentence = [*'hvbbdz']
x = torch.zeros((1, len(sentence)), dtype=int)
for j, w in enumerate(sentence):
    if j >= MAX_LEN:
        break
    x[0, j] = CHAR_TO_INDEX.get(w, CHAR_TO_INDEX['none'])

In [96]:
'maggie'

'maggie'

In [97]:
x.shape

torch.Size([1, 6])

In [98]:
for i in range(len(sentence)):
    letter = x[0][i].reshape(-1, 1)
    print( INDEX_TO_CHAR[torch.argmax(model(letter))] )

z
z
v
v
v
z


'z'

In [38]:
for ep in range(10):
    start = time.time()
    train_loss = 0.
    train_passed = 0

    for i in range(int(len(X) / 100)):
        batch = X[i * 100:(i + 1) * 100]
        X_batch = batch[:, :-1]
        Y_batch = batch[:, 1:].flatten()

        optimizer.zero_grad()
        answers, _ = model.forward(X_batch)
        answers = answers.view(-1, len(INDEX_TO_CHAR))
        loss = criterion(answers, Y_batch)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        train_passed += 1

    print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(ep, time.time() - start, train_loss / train_passed))
    generate_sentence()

Epoch 0. Time: 2.762, Train loss: 1.530
helloe l   toaaohutd     toooohun     toooohun     tooo
Epoch 1. Time: 2.736, Train loss: 1.519
helloe l   toaaohutd     toooohun     toooohun     tooo
Epoch 2. Time: 2.729, Train loss: 1.509
helloe l n toooah n   toaoooutn     toooohun     tooooh
Epoch 3. Time: 2.761, Train loss: 1.500
helloe l n toooah n   toaoooutn     toooohun     tooooh
Epoch 4. Time: 2.746, Train loss: 1.491
helloe l n toooth n  etoaoahnnn     toooohun     tooooh
Epoch 5. Time: 2.932, Train loss: 1.483
helloe l n toooth n  etoaoahnnn     toooohun     tooooh
Epoch 6. Time: 2.804, Train loss: 1.475
helloe l n toooth n  etoaoahnnn     tooooounn     toooo
Epoch 7. Time: 2.790, Train loss: 1.467
helloe l n toooth n  etoaoahnnn     tooooounn     toooo
Epoch 8. Time: 3.052, Train loss: 1.459
helloe l n toooth n  etoaoahnnn     tooooornn     toooo
Epoch 9. Time: 3.189, Train loss: 1.452
helloe l n toooth nn eto tr ntheto e  ntraooaennnn     
